name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Assemble Release Bundle
      run: |
        ./gradlew bundleRelease

    - name: Sign Release Android
      uses: r0adkll/sign-android-release@v1
      id: sign_app_android
      with:
        releaseDirectory: androidApp/build/outputs/bundle/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}

    - name: Sign Release Wear OS
      uses: r0adkll/sign-android-release@v1
      id: sign_app_wear
      with:
        releaseDirectory: wearApp/build/outputs/bundle/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}


    - name: Upload release Android
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        packageName: nl.tiebe.otarium
        releaseFiles: ${{steps.sign_app_android.outputs.signedReleaseFile}}
        track: qa
        whatsNewDirectory: whatsNew

    - name: Upload release Wear OS
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        packageName: nl.tiebe.otarium
        releaseFiles: ${{steps.sign_app_wear.outputs.signedReleaseFile}}
        track: wear:qa
        whatsNewDirectory: whatsNew