name: Android CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Assemble Release Bundle
      run: |
        ./gradlew bundleRelease
    - name: Sign Release Android
      uses: r0adkll/sign-android-release@v1
      id: sign_app_android
      with:
        releaseDirectory: androidApp/build/outputs/bundle/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}

    - name: Sign Release Wear OS
      uses: r0adkll/sign-android-release@v1
      id: sign_app_wear
      with:
        releaseDirectory: wearApp/build/outputs/bundle/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}


    - name: Upload release
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        packageName: nl.tiebe.otarium
        releaseFiles: ${{steps.sign_app_android.outputs.signedReleaseFile}},${{steps.sign_app_wear.outputs.signedReleaseFile}}
        track: production
        whatsNewDirectory: whatsNew
        changesNotSentForReview: true


    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        # Artifact name
        name: otarium.apk
        # A file, directory or wildcard pattern that describes what to upload
        path: androidApp/build/outputs/apk/debug/androidApp-debug.apk
