name: iOS starter workflow

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and publish
        uses: sparkfabrik/ios-build-action@v2.1.0
        with:
          upload-to-testflight: true
          increment-build-number: true
          build-pods: true
          pods-path: "iosApp/Podfile"
          configuration: Release
          export-method: app-store
          workspace-path: iosApp/iosApp.xcodeproj
          project-path: iosApp/iosApp.xcworkspace
          scheme: iosApp
          output-path: build-${{ github.sha }}.ipa
          apple-key-id: ${{ secrets.APPLE_KEY_ID }}
          apple-key-issuer-id: ${{ secrets.APPLE_KEY_ISSUER_ID }}
          apple-key-content: ${{ secrets.APPLE_KEY_CONTENT }}
          team-id: ${{ secrets.TEAM_ID }}
          team-name: ${{ secrets.TEAM_NAME }}
          match-password: ${{ secrets.MATCH_PASSWORD }}
          match-git-url: ${{ secrets.MATCH_GIT_URL }}
          match-git-basic-authorization: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          match-build-type: "appstore"
          browserstack-upload: false
          browserstack-username: ${{ secrets.BROWSERSTACK_USERNAME }}
          browserstack-access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          fastlane-env: stage
          ios-app-id: ${{ secrets.APP_ID }}
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Otarium.ipa
          path: build-${{ github.sha }}.ipa
